CREATE TABLE AGENTS (
    ID integer NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NICKNAME varchar(255),
    AGE integer,
    PHONE_NUMBER varchar(15)
);

CREATE TABLE MISSIONS (
    ID integer NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CODENAME varchar(255),
    OBJECTIVE varchar(255),
    LOCATION varchar(255),
    NOTES varchar(255)
);

CREATE TABLE ASSIGNMENTS (
    ID integer NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    AGENT_ID integer,
    MISSION_ID integer,
    --START_DATE varchar(255),
    --END_DATE varchar(255),
    START_DATE bigint,
    END_DATE bigint,
    FOREIGN KEY (AGENT_ID) REFERENCES AGENTS(ID),
    FOREIGN KEY (MISSION_ID) REFERENCES MISSIONS(ID)
);

    
